DROP TABLE IF EXISTS TASK_CONFORMITY;
DROP TABLE IF EXISTS TASK_SEQUENCE;
DROP TABLE IF EXISTS TASK_POINT_ANSWERS;
DROP TABLE IF EXISTS TASK_POINT_VARIANTS;
DROP TABLE IF EXISTS TASK_POINTS;
DROP TABLE IF EXISTS QUESTION;