CREATE TABLE IF NOT EXISTS QUESTION
(
    ID              uuid PRIMARY KEY,
    DESCRIPTION     VARCHAR(255) NOT NULL,
    QUESTION_TYPE   smallint     NOT NULL,
    RANK            smallint     NOT NULL,
    INDICATOR_ID    UUID         NOT NULL REFERENCES INDICATOR (ID),
    COMPLETE_ANSWER VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TASK_POINTS
(
    ID          SERIAL PRIMARY KEY,
    QUESTION_ID uuid REFERENCES QUESTION (ID) ON DELETE CASCADE,
    SINGLE      BOOLEAN
);

CREATE TABLE IF NOT EXISTS TASK_POINT_VARIANTS
(
    ID            SERIAL PRIMARY KEY,
    TASK_POINT_ID SERIAL REFERENCES TASK_POINTS (ID) ON DELETE CASCADE ,
    VARIANT       TEXT
);

CREATE TABLE IF NOT EXISTS TASK_POINT_ANSWERS
(
    ID            SERIAL PRIMARY KEY,
    TASK_POINT_ID SERIAL REFERENCES TASK_POINTS (ID) ON DELETE CASCADE,
    ANSWER        INT
);


CREATE TABLE IF NOT EXISTS TASK_SEQUENCE
(
    ID          SERIAL PRIMARY KEY,
    ANSWER      VARCHAR(255) NOT NULL,
    SEQUENCE    smallint     NOT NULL,
    QUESTION_ID uuid REFERENCES QUESTION (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TASK_CONFORMITY
(
    ID          SERIAL PRIMARY KEY,
    LEFT_VALUE  VARCHAR(255) NOT NULL,
    RIGHT_VALUE VARCHAR(255) NOT NULL,
    QUESTION_ID uuid REFERENCES QUESTION (ID) ON DELETE CASCADE
);
