CREATE TABLE IF NOT EXISTS COMPETENCY
(
    ID              UUID PRIMARY KEY,
    CODE            VARCHAR(12)  NOT NULL,
    TITLE           VARCHAR(255) NOT NULL,
    CATEGORY        VARCHAR(255) NOT NULL,
    COMPETENCY_TYPE SMALLINT     NOT NULL,
    LEVEL_ID        UUID REFERENCES LEVEL (ID) ON DELETE CASCADE,
    UGSN_ID         UUID REFERENCES UGSN (ID) ON DELETE CASCADE,
    SPECIALTY_ID    UUID REFERENCES SPECIALTY (ID) ON DELETE CASCADE,
    PROGRAM_ID      UUID REFERENCES PROGRAM (ID) ON DELETE CASCADE
);