http:
  port: ${HTTP_PORT:8080}
  readTimeout: 4s
  writeTimeout: 10s
  shutdownTimeout: 10s

postgres:
  host: ${POSTGRES_HOST:localhost}
  port: ${POSTGRES_PORT:5432}
  databaseName: ${POSTGRES_DATABASE:constructor}
  username: ${POSTGRES_USERNAME:postgres}
  password: ${POSTGRES_PASSWORD:root}
  sslMode: ${POSTGRES_SSL_MODE:false}

