http:
  port: ${HTTP_PORT:8080}
  readTimeout: 4s
  writeTimeout: 10s
  shutdownTimeout: 10s

mongo:
  uri: ${MONGO_URI}
  databaseName: ${MONGO_DATABASE:constructor}
  username: ${MONGO_USERNAME:admin}
  password: ${MONGO_PASSWORD:root}
  disconnectTimeout: 10s

logger:
  level: debug
  lig: zap

