// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.3 DO NOT EDIT.
package v1

import (
	"fmt"
	"net/http"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/go-chi/chi/v5"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Returns specialty with such code.
	// (GET /specialties/{specialtyCode})
	GetSpecificSpecialty(w http.ResponseWriter, r *http.Request, specialtyCode string)
	// Returns programs with such specialty code.
	// (GET /specialties/{specialtyCode}/program)
	GetPrograms(w http.ResponseWriter, r *http.Request, specialtyCode string)
	// Adding program for specialty
	// (POST /specialties/{specialtyCode}/program)
	AddedProgram(w http.ResponseWriter, r *http.Request, specialtyCode string)
	// Returns ugsn.
	// (GET /ugsn)
	GetUgsn(w http.ResponseWriter, r *http.Request)
	// create ugsn
	// (POST /ugsn)
	CreateUgsn(w http.ResponseWriter, r *http.Request)
	// Returns ugsn with such code.
	// (GET /ugsn/{ugsnCode})
	GetSpecificUgsn(w http.ResponseWriter, r *http.Request, ugsnCode string)
	// Returns specialties with such code ugsn.
	// (GET /ugsn/{ugsnCode}/specialties)
	GetSpecialties(w http.ResponseWriter, r *http.Request, ugsnCode string)
	// Adding specialties for ugsn
	// (POST /ugsn/{ugsnCode}/specialties)
	AddedSpecialties(w http.ResponseWriter, r *http.Request, ugsnCode string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetSpecificSpecialty operation middleware
func (siw *ServerInterfaceWrapper) GetSpecificSpecialty(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "specialtyCode" -------------
	var specialtyCode string

	err = runtime.BindStyledParameterWithLocation("simple", false, "specialtyCode", runtime.ParamLocationPath, chi.URLParam(r, "specialtyCode"), &specialtyCode)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "specialtyCode", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpecificSpecialty(w, r, specialtyCode)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetPrograms operation middleware
func (siw *ServerInterfaceWrapper) GetPrograms(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "specialtyCode" -------------
	var specialtyCode string

	err = runtime.BindStyledParameterWithLocation("simple", false, "specialtyCode", runtime.ParamLocationPath, chi.URLParam(r, "specialtyCode"), &specialtyCode)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "specialtyCode", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPrograms(w, r, specialtyCode)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AddedProgram operation middleware
func (siw *ServerInterfaceWrapper) AddedProgram(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "specialtyCode" -------------
	var specialtyCode string

	err = runtime.BindStyledParameterWithLocation("simple", false, "specialtyCode", runtime.ParamLocationPath, chi.URLParam(r, "specialtyCode"), &specialtyCode)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "specialtyCode", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddedProgram(w, r, specialtyCode)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetUgsn operation middleware
func (siw *ServerInterfaceWrapper) GetUgsn(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUgsn(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateUgsn operation middleware
func (siw *ServerInterfaceWrapper) CreateUgsn(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUgsn(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetSpecificUgsn operation middleware
func (siw *ServerInterfaceWrapper) GetSpecificUgsn(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "ugsnCode" -------------
	var ugsnCode string

	err = runtime.BindStyledParameterWithLocation("simple", false, "ugsnCode", runtime.ParamLocationPath, chi.URLParam(r, "ugsnCode"), &ugsnCode)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ugsnCode", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpecificUgsn(w, r, ugsnCode)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetSpecialties operation middleware
func (siw *ServerInterfaceWrapper) GetSpecialties(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "ugsnCode" -------------
	var ugsnCode string

	err = runtime.BindStyledParameterWithLocation("simple", false, "ugsnCode", runtime.ParamLocationPath, chi.URLParam(r, "ugsnCode"), &ugsnCode)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ugsnCode", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpecialties(w, r, ugsnCode)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AddedSpecialties operation middleware
func (siw *ServerInterfaceWrapper) AddedSpecialties(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "ugsnCode" -------------
	var ugsnCode string

	err = runtime.BindStyledParameterWithLocation("simple", false, "ugsnCode", runtime.ParamLocationPath, chi.URLParam(r, "ugsnCode"), &ugsnCode)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ugsnCode", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddedSpecialties(w, r, ugsnCode)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshallingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshallingParamError) Error() string {
	return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/specialties/{specialtyCode}", wrapper.GetSpecificSpecialty)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/specialties/{specialtyCode}/program", wrapper.GetPrograms)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/specialties/{specialtyCode}/program", wrapper.AddedProgram)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ugsn", wrapper.GetUgsn)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ugsn", wrapper.CreateUgsn)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ugsn/{ugsnCode}", wrapper.GetSpecificUgsn)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ugsn/{ugsnCode}/specialties", wrapper.GetSpecialties)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ugsn/{ugsnCode}/specialties", wrapper.AddedSpecialties)
	})

	return r
}
