// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.3 DO NOT EDIT.
package v1

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Defines values for ErrorSlug.
const (
	BadRequest ErrorSlug = "bad-request"
)

// Error defines model for Error.
type Error struct {
	Details string    `json:"details"`
	Slug    ErrorSlug `json:"slug"`
}

// ErrorSlug defines model for ErrorSlug.
type ErrorSlug string

// ProgramResponse defines model for ProgramResponse.
type ProgramResponse struct {
	Id            openapi_types.UUID `json:"id"`
	SpecialtyCode string             `json:"specialtyCode"`
	Title         string             `json:"title"`
}

// SpecialtiesRequest defines model for SpecialtiesRequest.
type SpecialtiesRequest struct {
	Code  string `json:"code"`
	Title string `json:"title"`
}

// SpecialtiesResponse defines model for SpecialtiesResponse.
type SpecialtiesResponse struct {
	Code     string `json:"code"`
	Title    string `json:"title"`
	UgsnCode string `json:"ugsnCode"`
}

// SpecificSpecialtyResponse defines model for SpecificSpecialtyResponse.
type SpecificSpecialtyResponse struct {
	Code     string      `json:"code"`
	Program  interface{} `json:"program"`
	Title    string      `json:"title"`
	UgsnCode string      `json:"ugsnCode"`
}

// SpecificUgsnResponse defines model for SpecificUgsnResponse.
type SpecificUgsnResponse struct {
	Code      string      `json:"code"`
	Specialty interface{} `json:"specialty"`
	Title     string      `json:"title"`
}

// UgsnRequest defines model for UgsnRequest.
type UgsnRequest struct {
	Code  string `json:"code"`
	Title string `json:"title"`
}

// UgsnResponse defines model for UgsnResponse.
type UgsnResponse struct {
	Code  string `json:"code"`
	Title string `json:"title"`
}

// AddedProgramJSONBody defines parameters for AddedProgram.
type AddedProgramJSONBody = []string

// AddedSpecialtiesJSONBody defines parameters for AddedSpecialties.
type AddedSpecialtiesJSONBody = interface{}

// AddedProgramJSONRequestBody defines body for AddedProgram for application/json ContentType.
type AddedProgramJSONRequestBody = AddedProgramJSONBody

// CreateUgsnJSONRequestBody defines body for CreateUgsn for application/json ContentType.
type CreateUgsnJSONRequestBody = UgsnRequest

// AddedSpecialtiesJSONRequestBody defines body for AddedSpecialties for application/json ContentType.
type AddedSpecialtiesJSONRequestBody = AddedSpecialtiesJSONBody
